name: Upload

on:
  push:
    branches:
      - master

jobs:
  resume:
    name: Compile and upload resume to Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v3
        with:
          working_directory: "src/assets"
          root_file: resume.tex
      - uses: MrFlynn/upload-to-netlify-action@v3
        with:
          source-file: "src/assets/resume.pdf"
          destination-path: "/resume.pdf"
          site-name: pleatsikas-me
          netlify-token: ${{ secrets.NETLIFY_TOKEN }}
          branch-name: master
